.TH "Billboard" 3 "Thu Mar 9 2017" "Networking_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Billboard \- Class to rotate a UIElement in the world to face the main camera  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Class to rotate a UIElement in the world to face the main camera 



.SH "Author"
.PP 
Generated automatically by Doxygen for Networking_Project from the source code\&.
