.TH "Bullet" 3 "Thu Mar 9 2017" "Networking_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bullet \- \fBBullet\fP behavior  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBm_bulletDamage\fP = 10"
.br
.RI "\fIDamage done by each bullet \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBBullet\fP behavior 


.SH "Member Data Documentation"
.PP 
.SS "int Bullet\&.m_bulletDamage = 10"

.PP
Damage done by each bullet 

.SH "Author"
.PP 
Generated automatically by Doxygen for Networking_Project from the source code\&.
