.TH "EnemySpawner" 3 "Thu Mar 9 2017" "Networking_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemySpawner \- Class used to spawn enemies  

.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStartServer\fP ()"
.br
.RI "\fIOverride: function called on the server / Generate a random number of enemies \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBm_enemyPrefab\fP"
.br
.RI "\fIPrefab to instantiate for the enemies \fP"
.ti -1c
.RI "int \fBm_numberOfEnemies\fP"
.br
.RI "\fIEnemies number to spawn \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class used to spawn enemies 


.SH "Member Function Documentation"
.PP 
.SS "override void EnemySpawner\&.OnStartServer ()"

.PP
Override: function called on the server / Generate a random number of enemies 
.SH "Member Data Documentation"
.PP 
.SS "GameObject EnemySpawner\&.m_enemyPrefab"

.PP
Prefab to instantiate for the enemies 
.SS "int EnemySpawner\&.m_numberOfEnemies"

.PP
Enemies number to spawn 

.SH "Author"
.PP 
Generated automatically by Doxygen for Networking_Project from the source code\&.
