.TH "PlayerController" 3 "Thu Mar 9 2017" "Networking_Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits NetworkBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStartLocalPlayer\fP ()"
.br
.RI "\fIOverride: Behavior only done by the local player at the start \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBm_scaleHorizontal\fP = 150\&.0f"
.br
.ti -1c
.RI "float \fBm_scaleVertical\fP = 3\&.0f"
.br
.ti -1c
.RI "GameObject \fBm_bulletPrefab\fP"
.br
.RI "\fIFields for the bullet \fP"
.ti -1c
.RI "Transform \fBm_bulletSpawn\fP"
.br
.ti -1c
.RI "float \fBm_bulletSpeed\fP = 6\&.0f"
.br
.ti -1c
.RI "float \fBm_bulletLifeTime\fP = 2\&.0f"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void PlayerController\&.OnStartLocalPlayer ()"

.PP
Override: Behavior only done by the local player at the start 
.SH "Member Data Documentation"
.PP 
.SS "float PlayerController\&.m_bulletLifeTime = 2\&.0f"

.SS "GameObject PlayerController\&.m_bulletPrefab"

.PP
Fields for the bullet 
.SS "Transform PlayerController\&.m_bulletSpawn"

.SS "float PlayerController\&.m_bulletSpeed = 6\&.0f"

.SS "float PlayerController\&.m_scaleHorizontal = 150\&.0f"

.SS "float PlayerController\&.m_scaleVertical = 3\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for Networking_Project from the source code\&.
